-- Long-lived, revocable login sessions for the API. The raw token only ever exists in the user's
-- cookie; we store its SHA-256 hash, so a leaked table can't be used to log in.
CREATE TABLE refresh_tokens (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    -- Every token rotated from the same login shares a family, so one stolen token can revoke them all.
    family_id   UUID        NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Set when the token is rotated (exchanged for a new one) or revoked (logout, theft).
    -- From then on it is never accepted again.
    revoked_at  TIMESTAMPTZ
);

CREATE INDEX refresh_tokens_family_id_idx ON refresh_tokens (family_id);
