CREATE TABLE users (
    id                        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255) NOT NULL CHECK (char_length(name) BETWEEN 1 AND 255),
    email                     VARCHAR(255) NOT NULL UNIQUE,
    password                  VARCHAR(255) NOT NULL,
    language                  VARCHAR(5)   NOT NULL DEFAULT 'fr' CHECK (language IN ('fr', 'nl', 'en')),
    two_factor_secret         VARCHAR(255),
    two_factor_recovery_codes TEXT,
    email_verified_at         TIMESTAMPTZ,
    photo_path                VARCHAR(2048),
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at                TIMESTAMPTZ
);
