CREATE TABLE asbls (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denomination      VARCHAR(255) NOT NULL,
    bce_number        VARCHAR(12)  NOT NULL UNIQUE,
    ubo_number        VARCHAR(20),
    address           VARCHAR(255),
    slug              VARCHAR(255) NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]+$'),
    default_language  VARCHAR(5)   NOT NULL DEFAULT 'fr'         CHECK (default_language IN ('fr', 'nl', 'en')),
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING'    CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED')),
    stripe_account_id VARCHAR(255),
    logo_path         VARCHAR(2048),
    cover_path        VARCHAR(2048),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ
);
