CREATE TABLE events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asbl_id     BIGINT       NOT NULL REFERENCES asbls(id),
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    starts_at   TIMESTAMPTZ  NOT NULL,
    location    VARCHAR(255),
    visibility  VARCHAR(20)  NOT NULL DEFAULT 'PUBLIC' CHECK (visibility IN ('PUBLIC', 'MEMBERS')),
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'  CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED', 'ENDED')),
    cover_path  VARCHAR(2048),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ
);
