CREATE TABLE payables (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type     VARCHAR(20)  NOT NULL CHECK (type IN ('MEMBERSHIP', 'REGISTRATION', 'DONATION')),
    amount   NUMERIC(8,2) NOT NULL CHECK (amount >= 0),
    currency VARCHAR(3)   NOT NULL DEFAULT 'EUR',
    CHECK (amount > 0 OR type <> 'DONATION')
);

CREATE TABLE registrations (
    id                 BIGINT      PRIMARY KEY REFERENCES payables(id) ON DELETE CASCADE,
    event_id           BIGINT      NOT NULL REFERENCES events(id),
    ticket_category_id BIGINT      NOT NULL REFERENCES ticket_categories(id),
    user_id            BIGINT      REFERENCES users(id),
    guest_email        VARCHAR(255),
    status             VARCHAR(20) NOT NULL DEFAULT 'RESERVED'
                       CHECK (status IN ('RESERVED', 'PAID', 'CONFIRMED', 'ATTENDED', 'CANCELLED', 'REFUNDED', 'EXPIRED')),
    qr_token           VARCHAR(64) UNIQUE,
    registered_at      TIMESTAMPTZ,
    checkin_at         TIMESTAMPTZ,
    CHECK (user_id IS NOT NULL OR guest_email IS NOT NULL)
);

CREATE TABLE payments (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asbl_id                  BIGINT       NOT NULL REFERENCES asbls(id),
    user_id                  BIGINT       REFERENCES users(id),
    payer_name               VARCHAR(255) NOT NULL,
    payer_email              VARCHAR(255) NOT NULL,
    payable_id               BIGINT       NOT NULL UNIQUE REFERENCES payables(id),
    stripe_payment_intent_id VARCHAR(255) UNIQUE,
    idempotency_key          VARCHAR(64)  UNIQUE,
    amount                   NUMERIC(8,2) NOT NULL CHECK (amount > 0),
    commission               NUMERIC(8,2) NOT NULL DEFAULT 0 CHECK (commission >= 0),
    status                   VARCHAR(20)  NOT NULL DEFAULT 'INITIATED'
                             CHECK (status IN ('INITIATED', 'SUCCEEDED', 'FAILED', 'REFUNDED')),
    paid_at                  TIMESTAMPTZ
);
