CREATE TABLE memberships (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    asbl_id     BIGINT      NOT NULL REFERENCES asbls(id) ON DELETE CASCADE,
    role        VARCHAR(20) NOT NULL DEFAULT 'MEMBER'  CHECK (role IN ('ADMIN', 'TREASURER', 'VIEWER', 'MEMBER')),
    category    VARCHAR(20) NOT NULL DEFAULT 'FULL'    CHECK (category IN ('FULL', 'SUPPORTER', 'HONORARY')),
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACTIVE', 'EXCLUDED', 'LEFT')),
    joined_at   DATE,
    excluded_at DATE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, asbl_id)
);
