CREATE TABLE ticket_categories (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT       NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    label       VARCHAR(100) NOT NULL,
    price       NUMERIC(8,2) NOT NULL CHECK (price >= 0),
    total_seats INT          NOT NULL CHECK (total_seats > 0),
    sold_seats  INT          NOT NULL DEFAULT 0 CHECK (sold_seats >= 0 AND sold_seats <= total_seats)
);
