CREATE TABLE audit_logs (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    asbl_id     BIGINT       REFERENCES asbls(id) ON DELETE SET NULL,
    action      VARCHAR(100) NOT NULL CHECK (char_length(action) BETWEEN 1 AND 100),
    entity_type VARCHAR(255),
    entity_id   BIGINT,
    payload     JSONB,
    ip          VARCHAR(45),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_asbl_created ON audit_logs (asbl_id, created_at DESC);
CREATE INDEX idx_audit_logs_created      ON audit_logs (created_at DESC);
